#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

/// <summary>
/// EditorUtility.CopySerialized also copies the template ScriptableObject name.
/// Generated CaseData assets therefore need their internal object name restored
/// to the asset filename after import. This removes Unity's
/// "Main Object Name does not match filename" warnings without changing the
/// package display name, API ID, drop pool, price, or progression settings.
/// </summary>
[InitializeOnLoad]
public static class GeneratedPackageAssetNameRepair
{
    private const string CollectionPrefix = "cc_collection_package_";
    private const string SouvenirPrefix = "cc_souvenir_package_";

    private static readonly HashSet<string> PendingPaths =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase);

    private static bool repairScheduled;

    static GeneratedPackageAssetNameRepair()
    {
        // Repairs assets generated by older versions once after scripts reload.
        EditorApplication.delayCall += RepairAllSilently;
    }

    [MenuItem("Case Curator/Containers/Repair Generated Package Asset Names")]
    public static void RepairAllFromMenu()
    {
        int repaired = RepairAllGeneratedPackages();

        EditorUtility.DisplayDialog(
            "Generated Package Names",
            repaired > 0
                ? $"Repaired {repaired} generated package asset name(s)."
                : "All generated package asset names already match their filenames.",
            "OK");
    }

    internal static void QueueImportedAssets(string[] importedAssets)
    {
        if (importedAssets == null)
            return;

        for (int i = 0; i < importedAssets.Length; i++)
        {
            string path = importedAssets[i];

            if (!string.IsNullOrWhiteSpace(path) &&
                path.EndsWith(".asset", StringComparison.OrdinalIgnoreCase))
            {
                PendingPaths.Add(path);
            }
        }

        if (PendingPaths.Count == 0 || repairScheduled)
            return;

        repairScheduled = true;
        EditorApplication.delayCall += RepairPendingAssets;
    }

    private static void RepairAllSilently()
    {
        RepairAllGeneratedPackages();
    }

    private static int RepairAllGeneratedPackages()
    {
        string[] guids = AssetDatabase.FindAssets("t:CaseData");
        int repaired = 0;

        for (int i = 0; i < guids.Length; i++)
        {
            string path = AssetDatabase.GUIDToAssetPath(guids[i]);

            if (RepairAssetAtPath(path))
                repaired++;
        }

        if (repaired > 0)
            AssetDatabase.SaveAssets();

        return repaired;
    }

    private static void RepairPendingAssets()
    {
        repairScheduled = false;

        if (PendingPaths.Count == 0)
            return;

        List<string> paths = new List<string>(PendingPaths);
        PendingPaths.Clear();
        int repaired = 0;

        for (int i = 0; i < paths.Count; i++)
        {
            if (RepairAssetAtPath(paths[i]))
                repaired++;
        }

        if (repaired > 0)
            AssetDatabase.SaveAssets();
    }

    private static bool RepairAssetAtPath(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
            return false;

        CaseData package = AssetDatabase.LoadAssetAtPath<CaseData>(path);

        if (!IsGeneratedPackage(package))
            return false;

        string expectedName = Path.GetFileNameWithoutExtension(path);

        if (string.IsNullOrWhiteSpace(expectedName) ||
            string.Equals(
                package.name,
                expectedName,
                StringComparison.Ordinal))
        {
            return false;
        }

        package.name = expectedName;
        EditorUtility.SetDirty(package);
        return true;
    }

    private static bool IsGeneratedPackage(CaseData package)
    {
        if (package == null || string.IsNullOrWhiteSpace(package.apiId))
            return false;

        return package.apiId.StartsWith(
                   CollectionPrefix,
                   StringComparison.OrdinalIgnoreCase) ||
               package.apiId.StartsWith(
                   SouvenirPrefix,
                   StringComparison.OrdinalIgnoreCase);
    }
}

public sealed class GeneratedPackageAssetNamePostprocessor : AssetPostprocessor
{
    private static void OnPostprocessAllAssets(
        string[] importedAssets,
        string[] deletedAssets,
        string[] movedAssets,
        string[] movedFromAssetPaths)
    {
        GeneratedPackageAssetNameRepair.QueueImportedAssets(importedAssets);
    }
}
#endif
