#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Builds Souvenir Hall as:
/// Museum Entrance -> Souvenir Hall -> Souvenir Collection -> all skins.
/// The generated collection categories deliberately skip the weapon browser.
/// </summary>
public static class MuseumSouvenirHallSetup
{
    public const string SouvenirHallWingId = "museum-souvenir-hall";

    private const string UnlockFolder = "Assets/Data/Museum/Unlocks";
    private const string UnlockPath =
        UnlockFolder + "/Unlock_SouvenirHall.asset";

    private sealed class CollectionInfo
    {
        public string stableId;
        public string displayName;
        public Sprite icon;
        public readonly HashSet<string> identifiers =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase);
    }

    [MenuItem("Tools/Case Curator/Museum/Apply Souvenir Hall")]
    public static void Apply()
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode)
        {
            EditorUtility.DisplayDialog(
                "Exit Play Mode",
                "Apply the Souvenir Hall setup outside Play Mode.",
                "OK");
            return;
        }

        GameDatabase database = FindTargetDatabase();

        if (database == null)
            return;

        if (database.museumCatalog == null)
        {
            EditorUtility.DisplayDialog(
                "Museum Catalog Missing",
                "Assign MuseumCatalogConfig on the selected GameDatabase first.",
                "OK");
            return;
        }

        if (!TryResolveRank(
                "Supreme Master First Class",
                out PlayerRank requiredRank))
        {
            EditorUtility.DisplayDialog(
                "Rank Not Found",
                "PlayerRank does not contain Supreme Master First Class.",
                "OK");
            return;
        }

        List<CollectionInfo> collections = CollectSouvenirCollections(database);

        if (collections.Count == 0)
        {
            EditorUtility.DisplayDialog(
                "No Souvenir Collections Found",
                "No non-Rare-Special SkinData with Can Be Souvenir enabled and " +
                "collection metadata was found in GameDatabase.allSkins.",
                "OK");
            return;
        }

        bool confirmed = EditorUtility.DisplayDialog(
            "Apply Souvenir Hall",
            $"Create or rebuild Souvenir Hall with {collections.Count} collection " +
            "categories. Each collection opens directly to all of its Souvenir " +
            "skins; the weapon-model page is skipped.",
            "Apply",
            "Cancel");

        if (!confirmed)
            return;

        EnsureFolder("Assets", "Data");
        EnsureFolder("Assets/Data", "Museum");
        EnsureFolder("Assets/Data/Museum", "Unlocks");

        UnlockDefinition unlock = GetOrCreateRankUnlock(requiredRank);
        RebuildCatalog(database.museumCatalog, collections, unlock);

        EditorUtility.SetDirty(database.museumCatalog);
        EditorUtility.SetDirty(database);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Selection.activeObject = database.museumCatalog;
        EditorGUIUtility.PingObject(database.museumCatalog);

        Debug.Log(
            $"Applied Souvenir Hall with {collections.Count} direct-to-skin " +
            "collection categories. Arsenal and Rare Special categories were " +
            "restricted to non-Souvenir variants.",
            database.museumCatalog);
    }

    private static void RebuildCatalog(
        MuseumCatalogConfig catalog,
        List<CollectionInfo> collections,
        UnlockDefinition unlock)
    {
        Undo.RecordObject(catalog, "Rebuild Souvenir Hall");

        if (catalog.wings == null)
            catalog.wings = new List<MuseumWingConfig>();

        MuseumWingConfig existingHall = FindWing(
            catalog.wings,
            SouvenirHallWingId,
            "souvenirhall");
        MuseumWingConfig hall = existingHall ?? new MuseumWingConfig();
        List<MuseumCategoryConfig> existingCategories =
            hall.categories != null
                ? new List<MuseumCategoryConfig>(hall.categories)
                : new List<MuseumCategoryConfig>();

        // Souvenir variants belong exclusively to Souvenir Hall. This also
        // corrects catalog assets generated by older setup versions where the
        // Arsenal filters still had Include Souvenir enabled.
        for (int wingIndex = 0; wingIndex < catalog.wings.Count; wingIndex++)
        {
            MuseumWingConfig wing = catalog.wings[wingIndex];

            if (wing == null || ReferenceEquals(wing, existingHall))
                continue;

            string wingId = Normalize(wing.wingId);

            if (wingId != Normalize(MuseumUnlockProgressionUtility.ArsenalWingId) &&
                wingId != Normalize(
                    MuseumUnlockProgressionUtility.RareSpecialVaultWingId))
            {
                continue;
            }

            if (wing.categories == null)
                continue;

            for (int categoryIndex = 0;
                 categoryIndex < wing.categories.Count;
                 categoryIndex++)
            {
                MuseumCategoryConfig category = wing.categories[categoryIndex];

                if (category == null || category.filter == null)
                    continue;

                category.openDirectlyToSkins = false;
                category.filter.includeSouvenir = false;
            }

            if (wingId == Normalize(MuseumUnlockProgressionUtility.ArsenalWingId))
            {
                wing.description =
                    "Normal and StatTrak weapon exhibits unlocked through the " +
                    "competitive rank ladder.";
            }
        }

        hall.wingId = SouvenirHallWingId;
        hall.displayName = "Souvenir Hall";
        hall.description =
            "Souvenir-only exhibits organised by Souvenir collection.";
        hall.sortOrder = 5;
        hall.includeInCompletion = true;
        hall.unlockDefinition = unlock;
        hall.categories = new List<MuseumCategoryConfig>();

        for (int i = 0; i < collections.Count; i++)
        {
            CollectionInfo info = collections[i];
            string categoryId =
                "museum-souvenir-collection-" + Slug(info.stableId);
            MuseumCategoryConfig category = FindCategory(
                existingCategories,
                categoryId,
                info.displayName) ?? new MuseumCategoryConfig();
            Sprite preservedIcon = category.icon;

            category.categoryId = categoryId;
            category.displayName = info.displayName;
            category.description =
                $"All Souvenir skins from {info.displayName}.";
            category.icon = preservedIcon != null ? preservedIcon : info.icon;
            category.sortOrder = i * 10;
            category.includeInCompletion = true;
            category.unlockDefinition = null;
            category.openDirectlyToSkins = true;
            category.filter = new MuseumCatalogFilter
            {
                filterMode = MuseumCatalogFilterMode.ListedCollections,
                collectionIds = new List<string>(info.identifiers),
                weaponNames = new List<string>(),
                includeNormal = false,
                includeStatTrak = false,
                includeSouvenir = true,
                includeVanilla = false
            };

            hall.categories.Add(category);
        }

        bool hallPresent = false;

        for (int i = 0; i < catalog.wings.Count; i++)
        {
            if (ReferenceEquals(catalog.wings[i], existingHall))
            {
                catalog.wings[i] = hall;
                hallPresent = true;
                break;
            }
        }

        if (!hallPresent)
            catalog.wings.Add(hall);
    }

    private static List<CollectionInfo> CollectSouvenirCollections(
        GameDatabase database)
    {
        Dictionary<string, CollectionInfo> byStableId =
            new Dictionary<string, CollectionInfo>(
                StringComparer.OrdinalIgnoreCase);

        if (database == null || database.allSkins == null)
            return new List<CollectionInfo>();

        for (int i = 0; i < database.allSkins.Count; i++)
        {
            SkinData skin = database.allSkins[i];

            if (skin == null ||
                !skin.canBeSouvenir ||
                skin.isVanilla ||
                skin.rarity == Rarity.RareSpecial)
            {
                continue;
            }

            string apiId = skin.collectionData != null
                ? Clean(skin.collectionData.apiId)
                : "";
            string dataName = skin.collectionData != null
                ? Clean(skin.collectionData.collectionName)
                : "";
            string legacyName = Clean(skin.collection);
            string displayName = !string.IsNullOrWhiteSpace(dataName)
                ? dataName
                : legacyName;
            string stableId = !string.IsNullOrWhiteSpace(apiId)
                ? apiId
                : displayName;

            if (string.IsNullOrWhiteSpace(stableId) ||
                string.IsNullOrWhiteSpace(displayName))
            {
                continue;
            }

            if (!byStableId.TryGetValue(stableId, out CollectionInfo info))
            {
                info = new CollectionInfo
                {
                    stableId = stableId,
                    displayName = displayName,
                    icon = skin.collectionData != null
                        ? skin.collectionData.icon
                        : null
                };
                byStableId.Add(stableId, info);
            }

            AddIdentifier(info.identifiers, apiId);
            AddIdentifier(info.identifiers, dataName);
            AddIdentifier(info.identifiers, legacyName);
        }

        List<CollectionInfo> result =
            new List<CollectionInfo>(byStableId.Values);
        result.Sort((a, b) => string.Compare(
            a != null ? a.displayName : "",
            b != null ? b.displayName : "",
            StringComparison.OrdinalIgnoreCase));
        return result;
    }

    private static void AddIdentifier(
        HashSet<string> identifiers,
        string value)
    {
        if (identifiers != null && !string.IsNullOrWhiteSpace(value))
            identifiers.Add(value.Trim());
    }

    private static UnlockDefinition GetOrCreateRankUnlock(
        PlayerRank minimumRank)
    {
        UnlockDefinition definition =
            AssetDatabase.LoadAssetAtPath<UnlockDefinition>(UnlockPath);

        if (definition == null)
        {
            definition = ScriptableObject.CreateInstance<UnlockDefinition>();
            AssetDatabase.CreateAsset(definition, UnlockPath);
        }

        Undo.RecordObject(definition, "Update Souvenir Hall unlock");
        definition.unlockId = SouvenirHallWingId;
        definition.featureId = FeatureId.Custom;
        definition.displayName = "Souvenir Hall";
        definition.requirementMode = UnlockRequirementGroupMode.All;
        definition.noRequirementsMeansUnlocked = false;
        definition.requirements = new List<UnlockRequirement>
        {
            new UnlockRequirement
            {
                requirementType = UnlockRequirementType.PlayerRankAtLeast,
                minimumRank = minimumRank,
                lockedReasonOverride =
                    "Reach Supreme Master First Class to unlock Souvenir Hall."
            }
        };

        EditorUtility.SetDirty(definition);
        return definition;
    }

    private static MuseumWingConfig FindWing(
        List<MuseumWingConfig> wings,
        string exactId,
        string normalizedNameTerm)
    {
        if (wings == null)
            return null;

        string normalizedId = Normalize(exactId);

        for (int i = 0; i < wings.Count; i++)
        {
            MuseumWingConfig wing = wings[i];

            if (wing != null && Normalize(wing.wingId) == normalizedId)
                return wing;
        }

        for (int i = 0; i < wings.Count; i++)
        {
            MuseumWingConfig wing = wings[i];

            if (wing != null &&
                Normalize(wing.DisplayName).Contains(normalizedNameTerm))
            {
                return wing;
            }
        }

        return null;
    }

    private static MuseumCategoryConfig FindCategory(
        List<MuseumCategoryConfig> categories,
        string exactId,
        string displayName)
    {
        if (categories == null)
            return null;

        string normalizedId = Normalize(exactId);
        string normalizedName = Normalize(displayName);

        for (int i = 0; i < categories.Count; i++)
        {
            MuseumCategoryConfig category = categories[i];

            if (category == null)
                continue;

            if (Normalize(category.categoryId) == normalizedId ||
                Normalize(category.DisplayName) == normalizedName)
            {
                return category;
            }
        }

        return null;
    }

    private static bool TryResolveRank(
        string displayName,
        out PlayerRank rank)
    {
        string target = Normalize(displayName);
        Array values = Enum.GetValues(typeof(PlayerRank));

        foreach (object value in values)
        {
            PlayerRank candidate = (PlayerRank)value;

            if (Normalize(candidate.ToString()) == target ||
                Normalize(
                    PlayerProgressUtility.GetRankDisplayName(candidate)) == target)
            {
                rank = candidate;
                return true;
            }
        }

        rank = default(PlayerRank);
        return false;
    }

    private static GameDatabase FindTargetDatabase()
    {
        if (Selection.activeObject is GameDatabase selected)
            return selected;

        string[] guids = AssetDatabase.FindAssets("t:GameDatabase");

        if (guids == null || guids.Length == 0)
        {
            EditorUtility.DisplayDialog(
                "GameDatabase Not Found",
                "Create or select a GameDatabase asset, then run this command again.",
                "OK");
            return null;
        }

        if (guids.Length > 1)
        {
            EditorUtility.DisplayDialog(
                "Select GameDatabase",
                "More than one GameDatabase exists. Select the intended asset " +
                "in the Project window, then run this command again.",
                "OK");
            return null;
        }

        string path = AssetDatabase.GUIDToAssetPath(guids[0]);
        return AssetDatabase.LoadAssetAtPath<GameDatabase>(path);
    }

    private static void EnsureFolder(string parent, string child)
    {
        string path = parent + "/" + child;

        if (!AssetDatabase.IsValidFolder(path))
            AssetDatabase.CreateFolder(parent, child);
    }

    private static string Slug(string value)
    {
        string normalized = Normalize(value);
        return string.IsNullOrWhiteSpace(normalized)
            ? "unknown"
            : normalized;
    }

    private static string Clean(string value)
    {
        return value != null ? value.Trim() : "";
    }

    private static string Normalize(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "";

        char[] buffer = new char[value.Length];
        int length = 0;

        for (int i = 0; i < value.Length; i++)
        {
            char character = value[i];

            if (!char.IsLetterOrDigit(character))
                continue;

            buffer[length++] = char.ToLowerInvariant(character);
        }

        return new string(buffer, 0, length);
    }
}
#endif
